version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    ports:
      - "13000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user123:password123@db:5432/db123

volumes:
  pgdata:
